Librinfo\SeedBatchBundle\Entity\Plot:
    type: entity

    fields:
        code:
            type:       string(255)
            nullable:   true

    oneToMany:
        seedBatches:
            targetEntity: Librinfo\SeedBatchBundle\Entity\SeedBatch
            mappedBy: plot
        certifications:
            targetEntity: Librinfo\SeedBatchBundle\Entity\Certification
            mappedBy: plot
            cascade: [ persist, remove ]
            orphanRemoval: true
            
    manyToOne:
        producer:
            targetEntity: Librinfo\CRMBundle\Entity\Organism
            inversedBy: plots
            joinColumn:
                name: producer_id
                referencedColumnName: id

    uniqueConstraints:
        search_idx:
            columns: [ producer_id, code ]